### ISSUE TITLE
Document this madness

### ISSUE THREAD

**Issue by ri0t** [c-base/meta#179]
There's a lot of confusion going on (essentially not a bad thing):
* [ ] Members want to know how to get in here
* [ ] Members want to know how to get rid of this
* [ ] Github possibly wants to know about our experience (we found bugs...)

**Comment by ri0t** [comment]
Get rid
====== 

The single place to adjust this for yourself: https://github.com/watching
To the top right ontop of the table is an "Unwatch all"-button - happy?
